accounts/urls.py
from django.urls import path
from . import views
# from .views import LoginView


app_name = 'accounts'
urlpatterns = [
    path('login/', views.login, name='login'),
    # path('login-api/', LoginView.as_view(), name='login_api'),
    path('logout/', views.logout, name='logout'),
    path('signup/', views.signup, name='signup'),
    path('delete/', views.delete, name='delete'),
    path('update/', views.update, name='update'),
    path('password/', views.change_password, name='change_password'),
    path('profile/<username>/', views.profile, name='profile'),
    path('<int:user_pk>/follow/', views.follow, name='follow'),
    path('<int:user_pk>/follower/', views.follower, name='follower'),
]

chat/urls.py
from django.urls import path

from . import views

app_name = 'chat'
urlpatterns = [
    path('', views.index, name='index'),
    path('<str:room_name>/', views.room, name='room'),
]

mango/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from . import views
from django.urls import path
# from accounts.views import LoginTemplateView, MyLoginView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.main, name='main'),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('allauth.urls')),
    path('posts/', include('posts.urls')),
    path('chat/', include('chat.urls')),
    path('my_messages/', include('my_messages.urls')),
    # 구글 정보 받아오기
    # path('login/', LoginTemplateView.as_view(), name='login'),
    # path('accounts/login/', MyLoginView.as_view(), name='account_login'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

my_messages/urls.py
from django.urls import path
from .views import MessageCreateView, MessageListView, SentMessagesView, ReplyMessageView
from . import views

app_name = 'my_messages'
urlpatterns = [
    path('send/', MessageCreateView.as_view(), name='send_message'),
    path('inbox/', MessageListView.as_view(), name='inbox_messages'),
    path('sent/', SentMessagesView.as_view(), name='sent_messages'),
    path('reply/<int:sender_id>/', ReplyMessageView.as_view(), name='reply'),
    path('<int:message_pk>/delete/', views.delete, name='delete'),
]

posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'
urlpatterns = [
    path('', views.index, name='index'),
    path('city/', views.city, name='city'),
    path('filtering/<str:sort>/', views.filtering, name='filtering'),
    path('city/filtering/<str:sort>/', views.city_filtering, name='city_filtering'),
    path('create/', views.create, name='create'),
    path('<int:post_pk>/', views.detail, name='detail'),
    path('<int:post_pk>/likes/', views.likes, name='likes'),
    path('<int:post_pk>/delete/', views.delete, name='delete'),
    path('<int:post_pk>/update/', views.update, name='update'),
    path('<int:post_pk>/reviews/', views.review_create, name='review_create'),
    path('<int:post_pk>/reviews/<int:review_pk>', views.review_update, name='review_update'),
    path('<int:post_pk>/reviews/<int:review_pk>/delete/', views.review_delete, name='review_delete'),
    path('<int:post_pk>/reviews/<int:review_pk>/likes/', views.review_likes, name='review_likes'),
    path('search/', views.search, name='search'),
    path('tags/<int:tag_pk>/', views.tagged_posts, name='tagged_posts'),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from imagekit.models import ProcessedImageField
from imagekit.processors import ResizeToFill
import os
from django.conf import settings

# Create your models here.
class User(AbstractUser):
    SEOUL = '서울'
    INCHEON = '인천'
    BUSAN = '부산'
    ULSAN = '울산'
    DAEGU = '대구'
    GWANGJU = '광주'
    DAEJEON = '대전'
    JEJU = '제주도'
    GYEONGGI = '경기도'
    GANGWON = '강원도'
    CHUNGBUK = '충청북도'
    CHUNGNAM = '충청남도'
    JEONBUK = '전라북도'
    JEONNAM = '전라남도'
    GYEONGBUK = '경상북도'
    GYEONGNAM = '경상남도'    
    REGION_CHOICES = [
        (SEOUL, '서울'), (INCHEON, '인천'), (BUSAN, '부산'), (ULSAN, '울산'), (DAEGU, '대구'), (GWANGJU, '광주'), (DAEJEON, '대전'), (JEJU, '제주도'), (GYEONGGI, '경기도'), (GANGWON, '강원도'), (CHUNGBUK, '충청북도'), (CHUNGNAM, '충청남도'), (JEONBUK, '전라북도'), (JEONNAM, '전라남도'), (GYEONGBUK, '경상북도'),(GYEONGNAM, '경상남도'),
    ]

    followings = models.ManyToManyField('self', related_name='followers', symmetrical=False)
    birthday = models.DateField(null = True, blank=True)
    def profile_image_path(instance, filename):
        return f'profile/{instance.pk}/{filename}'
    image = ProcessedImageField(upload_to=profile_image_path, blank=True, null=True)
    region = models.CharField(max_length=10, choices=REGION_CHOICES, default=SEOUL)


    def delete(self, *args, **kargs):
        if self.image:
            os.remove(os.path.join(settings.MEDIA_ROOT, self.image.path))
        super(User, self).delete(*args, **kargs)

    def save(self, *args, **kwargs):
        if self.id:
            old_user = User.objects.get(id=self.id)
            if self.image != old_user.image:
                if old_user.image:
                    os.remove(os.path.join(settings.MEDIA_ROOT, old_user.image.path))
        super(User, self).save(*args, **kwargs)    

posts/models.py
from django.db import models
from django.conf import settings
from imagekit.models import ProcessedImageField
from imagekit.processors import ResizeToFill
from django.core.validators import RegexValidator
from django.core.validators import MinValueValidator, MaxValueValidator
from django.utils import timezone
from datetime import timedelta,datetime
from django.conf import settings
import os
from taggit.managers import TaggableManager
from django.urls import reverse
from django.utils.text import slugify


class Post(models.Model):
    CAFE = 'cafe'
    BAKERY = 'bakery'
    CATEGORY_CHOICES = [
        (CAFE, 'Cafe'),
        (BAKERY, 'Bakery'),
    ]
    SEOUL = '서울'
    INCHEON = '인천'
    BUSAN = '부산'
    ULSAN = '울산'
    DAEGU = '대구'
    GWANGJU = '광주'
    DAEJEON = '대전'
    JEJU = '제주도'
    GYEONGGI = '경기도'
    GANGWON = '강원도'
    CHUNGBUK = '충청북도'
    CHUNGNAM = '충청남도'
    JEONBUK = '전라북도'
    JEONNAM = '전라남도'
    GYEONGBUK = '경상북도'
    GYEONGNAM = '경상남도'    
    CITY_CHOICES = [
        (SEOUL, '서울'), (INCHEON, '인천'), (BUSAN, '부산'), (ULSAN, '울산'), (DAEGU, '대구'), (GWANGJU, '광주'), (DAEJEON, '대전'), (JEJU, '제주도'), (GYEONGGI, '경기도'), (GANGWON, '강원도'), (CHUNGBUK, '충청북도'), (CHUNGNAM, '충청남도'), (JEONBUK, '전라북도'), (JEONNAM, '전라남도'), (GYEONGBUK, '경상북도'),(GYEONGNAM, '경상남도'),
    ]

    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    like_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='like_posts')
    title = models.CharField(max_length=50)
    category = models.CharField(max_length=10, choices=CATEGORY_CHOICES)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    address = models.CharField(max_length=200)
    phoneNumberRegex = RegexValidator(regex=r'^0[1-9]\d{0,2}-\d{3,4}-\d{4}$')
    phone = models.CharField(validators=[phoneNumberRegex], max_length=14)
    parking = models.CharField(max_length=50, default='가게 문의')
    business_time = models.CharField(max_length=50, default='가게 문의')
    menu = models.TextField()
    insta = models.URLField(blank=True, null=True)
    home = models.URLField(blank=True, null=True)
    city = models.CharField(max_length=10, choices=CITY_CHOICES)
    tags = TaggableManager()
    rating = models.DecimalField(default=0, max_digits=5, decimal_places=1)

    # slug = models.SlugField(allow_unicode=True)

    # def save(self, *args, **kwargs):
    #     if not self.slug:
    #         self.slug = slugify(self.title, allow_unicode=True)
    #     super(Post, self).save(*args, **kwargs)


    def __str__(self):
        return self.title

    @property
    def created_string(self):
        time = datetime.now(tz=timezone.utc) - self.created_at

        if time < timedelta(minutes=1):
            return '방금 전'
        elif time < timedelta(hours=1):
            return str(int(time.seconds / 60)) + '분 전'
        elif time < timedelta(days=1):
            return str(int(time.seconds / 3600)) + '시간 전'
        elif time < timedelta(days=7):
            time = datetime.now(tz=timezone.utc).date() - self.created_at.date()
            return str(time.days) + '일 전'
        else:
            return self.strftime('%Y-%m-%d')
    
    def delete(self, *args, **kargs):
        images = self.postimage_set.all()
        for image in images:
            image.delete()
        super(Post, self).delete(*args, **kargs)

class PostImage(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)

    def post_image_path(instance, filename):
        return f'post/{instance.post.pk}/{filename}'
    image = ProcessedImageField(
        upload_to=post_image_path,
        blank=True, 
        null=True,
        options={'quality':90})
    
    def delete(self, *args, **kargs):
        if self.image:
            os.remove(os.path.join(settings.MEDIA_ROOT, self.image.name))
            dir_path = os.path.dirname(os.path.join(settings.MEDIA_ROOT, self.image.name))
            if not os.listdir(dir_path):
                os.rmdir(dir_path)
        super(PostImage, self).delete(*args, **kargs)


    # def delete(self, *args, **kargs):
    #     if self.image:
    #         image_path = os.path.join(settings.MEDIA_ROOT, self.image.name)
    #         if os.path.exists(image_path):
    #             os.remove(image_path)
    #             dir_path = os.path.dirname(image_path)
    #             if not os.listdir(dir_path):
    #                 os.rmdir(dir_path)
    #     super(PostImage, self).delete(*args, **kargs)


class Review(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='reviews')
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    EMOTIONS = (
        (1, '별로에요'),
        (2, '괜찮아요'),
        (3, '맛있어요'),
    )
    emotion = models.IntegerField(choices=EMOTIONS, default=3)
    title = models.CharField(max_length=50)
    content = models.TextField()
    rating = models.IntegerField(default=5, validators=[MinValueValidator(1), MaxValueValidator(5)])
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    like_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='like_reviews')

    @property
    def created_string(self):
        time = datetime.now(tz=timezone.utc) - self.created_at

        if time < timedelta(minutes=1):
            return '방금 전'
        elif time < timedelta(hours=1):
            return str(int(time.seconds / 60)) + '분 전'
        elif time < timedelta(days=1):
            return str(int(time.seconds / 3600)) + '시간 전'
        elif time < timedelta(days=7):
            time = datetime.now(tz=timezone.utc).date() - self.created_at.date()
            return str(time.days) + '일 전'
        else:
            return self.strftime('%Y-%m-%d')
    
    def save(self, *args, **kwargs):
        self.post.rating = (self.post.rating*self.post.reviews.count() + self.rating) / (self.post.reviews.count() + 1)
        self.post.save()
        super(Review, self).save(*args, **kwargs)

# from django.core.exceptions import ValidationError  

# def validate_image_count(value):
#     if ReviewImage.objects.filter(review=value.review).count() > 3:
#         raise ValidationError('이미지는 최대 3개까지만 업로드 가능합니다.')


class ReviewImage(models.Model):
    review = models.ForeignKey(Review, on_delete=models.CASCADE)

    def review_image_path(instance, filename):
        return f'review/{instance.review.pk}/{filename}'
    image = ProcessedImageField(
        upload_to=review_image_path,
        blank=True, 
        null=True, 
        processors=[ResizeToFill(100, 100)], 
        options={'quality':100},)
    
    def delete(self, *args, **kargs):
        if self.image:
            os.remove(os.path.join(settings.MEDIA_ROOT, self.image.name))
        super(ReviewImage, self).delete(*args, **kargs)

    def save(self, *args, **kwargs):
        if self.id:
            old_post = ReviewImage.objects.get(id=self.id)
            if self.image != old_post.image:
                if old_post.image:
                    os.remove(os.path.join(settings.MEDIA_ROOT, old_post.image.name))
        super(ReviewImage, self).save(*args, **kwargs)
    

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.decorators import login_required
from .forms import CustomUserCreationForm, CustomUserChangeForm, CustomAuthenticationForm, CustomPasswordChangeForm
from django.http import JsonResponse

def login(request):
    if request.user.is_authenticated:
        return redirect('main')
    
    if request.method == 'POST':
        form = CustomAuthenticationForm(request, request.POST)
        if form.is_valid():
            auth_login(request, form.get_user())
            return redirect('posts:index')
    else:
        form = CustomAuthenticationForm()
    context = {
        'form': form,
    }
    return render(request, 'accounts/login.html', context)


@login_required
def logout(request):
    auth_logout(request)
    return redirect('posts:index')


def signup(request):
    if request.user.is_authenticated:
        return redirect('main')

    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('accounts:login')
    else:
        form = CustomUserCreationForm()
    context = {
        'form': form,
    }
    return render(request, 'accounts/signup.html', context)


@login_required
def delete(request):
    request.user.delete()
    return redirect('posts:index')


@login_required
def update(request):
    if request.method == 'POST':
        form = CustomUserChangeForm(request.POST, request.FILES, instance=request.user)
        if form.is_valid():
            form.save()
            return redirect('accounts:profile',request.user.username)
    else:
        form = CustomUserChangeForm(instance=request.user)
    context = {
        'form': form,
    }
    return render(request, 'accounts/update.html', context)


@login_required
def change_password(request):
    if request.method == 'POST':
        form = CustomPasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request, user)
            return redirect('posts:index')
    else:
        form = CustomPasswordChangeForm(request.user)
    context = {
        'form': form,
    }
    return render(request, 'accounts/change_password.html', context)



from django.contrib.auth import get_user_model

def profile(request, username):
    User = get_user_model()
    person = User.objects.get(username=username)
    context = {
        'person': person,
    }
    return render(request, 'accounts/profile.html', context)


@login_required
def follow(request, user_pk):
    User = get_user_model()
    you = User.objects.get(pk=user_pk)
    me = request.user

    if you != me:
        if me in you.followers.all():
            you.followers.remove(me)
            is_followed = False
        else:
            you.followers.add(me)
            is_followed = True
        context = {
            'is_followed': is_followed,
            'followings_count': you.followings.count(),
            'followers_count': you.followers.count(),
            'followings': [{'username': f.username, 'pk': f.pk} for f in you.followings.all()],
            'followers': [{'username': f.username,'pk': f.pk} for f in you.followers.all()]
        }
        
        return JsonResponse(context)
    return redirect('accounts:profile', you.username)

def follower(request, user_pk):
    User = get_user_model()
    user = User.objects.get(pk=user_pk)
    followers = [{'username': f.username, 'pk': f.pk} for f in user.followers.all()]
    return JsonResponse({'followers': followers})



# 구글 로그인 사용자 정보 받아오기
# from django.views.generic import TemplateView
# from allauth.account.views import LoginView
# from allauth.socialaccount.models import SocialAccount

# class MyLoginView(LoginView):
#     template_name = 'login.html'

#     def get_success_url(self):
#         # 로그인 후 사용자 정보 저장
#         user = self.request.user
#         social_account = SocialAccount.objects.get(user=user, provider='google')
#         extra_data = social_account.extra_data

#         # extra_data에서 사용자 정보 추출
#         first_name = extra_data.get('given_name')
#         last_name = extra_data.get('family_name')
#         email = extra_data.get('email')

#         # 데이터베이스에 저장
#         user.first_name = first_name
#         user.last_name = last_name
#         user.email = email
#         user.save()

#         return super().get_success_url()

# class LoginTemplateView(TemplateView):
#     template_name = 'login.html'

#     def get(self, request, *args, **kwargs):
#         if request.user.is_authenticated:
#             return redirect('home')
#         return super().get(request, *args, **kwargs)

# from django.views.generic import TemplateView

# class HomeView(TemplateView):
#     template_name = 'home.html'

#     def get(self, request, *args, **kwargs):
#         if request.user.is_authenticated:
#             return super().get(request, *args, **kwargs)
#         return redirect('account_login')

accounts/templates/accounts/profile.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Profile{% endblock title %}
{% block head %}
  <link rel="stylesheet" type="text/css" href="{% static 'css/profile.css' %}">
{% endblock head %}
{% block style %}
<style>
  section {
    position: relative;
  }
</style>
{% endblock style %}
{% block content %}
<a class="profile--backBtn" href="{% url 'main' %}"><뒤로</a>
  <div class="profile--box">
    <h1>{{ person.username }}님의 프로필 페이지
      {% if request.user.username != person.username %}
        <a href="{% url 'my_messages:reply' person.pk %}"><i class="bi bi-envelope-paper-heart chat--btn--txt"></i></a>
      {% endif %}
    </h1>
  
    <div class="profile--card">
      <div class="profile--image--box rounded-circle">
        {% if person.image %}
          <img src="{{ person.image.url }}" alt="" class="profile--img">
        {% else %}
          <img src="{% static 'image/profile-none.png' %}" alt="" class="profile--img">
        {% endif %}
      </div>
      <div class="profile--card--txt">
        <div class='d-flex align-items-center'>
          <p class="mb-0">이름 : {{ person.last_name }}
            {% if request.user == person %}
              <a href="{% url 'accounts:update' %}" class="profile--account--a">수정</a>
              <form action="{% url 'accounts:delete' %}" method="POST">
                {% csrf_token %}
                <input type="submit" class="profile--deleteBtn" value="탈퇴" onclick="return confirm('탈퇴 시, 더 이상 서비스를 이용하실 수 없습니다.\n정말 탈퇴하시겠습니까?')">
              </form> 
            {% endif %}
        </div>
          {% if request.user != person %}
            <div>
              <form id="follow-form" data-user-id="{{ person.pk }}">
                {% csrf_token %}
                {% if request.user in person.followers.all %}
                  <input class="profile--followbtn" type="submit" value="Unfollow">
                {% else %}
                  {% if request.user.is_authenticated %}
                    <input class="profile--followbtn" type="submit" value="follow">
                  {% else %}
                    <input class="profile--followbtn" type="submit" value="follow" disabled>
                  {% endif %}
                {% endif %}
              </form>
            </div>
          {% endif %}
        </p>
        <p>이메일 : {{ person.email }}</p>
        <p>생년월일 : {{ person.birthday }}</p>
        <p>선호지역 : {{ person.region }}</p>
        <!-- 팔로워 모달 버튼 -->
        <div>
          <button type="button" class="profile--followbtn" data-bs-toggle="modal" data-bs-target="#followersModal">
            <span id="followers-count">{{ person.followers.all|length }}</span> 팔로워
          </button>

          <!-- 팔로잉 모달 버튼 -->
          <button type="button" class="profile--followbtn" data-bs-toggle="modal" data-bs-target="#followingsModal">
            <span id = 'followings-count'>{{ person.followings.all|length }}</span> 팔로잉 
          </button>
        </div>
          <!-- 팔로워 Modal -->
          <div class="modal fade" id="followersModal" tabindex="-1" aria-labelledby="followersModalLabel" aria-hidden="true">
            <div class="modal-dialog">
              <div class="modal-content profile--modal--box">
                <div class="modal-header">
                  <h1 class="modal-title fs-5"  id="followersModalLabel">팔로워</h1>
                </div>
                <div class="modal-body row" id = "f_follower_list">
                  {% if request.user == person %}
                    {% for follower in person.followers.all %}
                      <div class="modal--profile--card col-3">
                        <a class="text-decoration-none link-secondary fw-bold modal--profile--link" href="{% url 'accounts:profile' follower.username %}">
                          {% if follower.image %}
                            <div class="profile--image rounded-circle">
                              <img src="{{ follower.image.url }}" alt="" class="object-fit-fill profile">
                            </div>
                          {% else %}
                            <div class="profile--image rounded-circle">
                              <img src="{% static 'image/profile-none.png' %}" alt="profile_image_none" class="object-fit-fill profile">
                            </div>
                          {% endif %}
                          <span>{{ follower }}</span></a>
                      </div>
                    {% endfor %}
                  {% else %}
                      <div class="row" id="followers-list"></div>
                  {% endif %}
                </div>
                <div class="modal-footer">
                  <button type="button" class="profile--followbtn" data-bs-dismiss="modal">Close</button>
                </div>
              </div>
            </div>
          </div>
          <!-- 팔로잉 Modal -->
          <div class="modal fade" id="followingsModal" tabindex="-1" aria-labelledby="followingsModalLabel" aria-hidden="true">
            <div class="modal-dialog">
              <div class="modal-content profile--modal--box">
                <div class="modal-header">
                  <h1 class="modal-title fs-5" id="followingsModalLabel">팔로잉</h1>
                </div>
                <div class="modal-body row">
                  {% for following in person.followings.all %}
                  <div class="modal--profile--card col-3">
                    <a class="text-decoration-none link-secondary fw-bold modal--profile--link" href="{% url 'accounts:profile' following.username %}">
                      {% if following.image %}
                        <div class="profile--image rounded-circle">
                          <img src="{{ following.image.url }}" alt="" class="object-fit-fill profile">
                        </div>
                      {% else %}
                        <div class="profile--image rounded-circle">
                          <img src="{% static 'image/profile-none.png' %}" alt="profile_image_none" class="object-fit-fill profile">
                        </div>
                      {% endif %}
                      <span>{{ following }}</span></a>
                  </div>
                  {% endfor %}
                </div>
                <div class="modal-footer">
                  <button type="button" class="profile--followbtn" data-bs-dismiss="modal">Close</button>
                </div>
              </div>
            </div>
          </div>
      </div>
    </div>
  </div>
  <div class="accordion accordion-flush" id="accordionFlushExample">
    <div class="accordion-item">
      <h2 class="accordion-header" id="flush-headingOne">
        <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#flush-collapseOne" aria-expanded="false" aria-controls="flush-collapseOne">
          {{ person.username }} 님이 작성한 모든 게시글
        </button>
      </h2>
      <div id="flush-collapseOne" class="accordion-collapse collapse" aria-labelledby="flush-headingOne">
        <div class="accordion-body">
          {% for post in person.post_set.all %}
            <div class="mb-1">
              <i class="bi bi-clipboard-check-fill"></i>
              <a class="profile--a" href="{% url 'posts:detail' post.pk %}">{{ post.title }}</a>
            </div>
            {% endfor %}
        </div>
      </div>
    </div>
    <div class="accordion-item">
      <h2 class="accordion-header" id="flush-headingTwo">
        <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#flush-collapseTwo" aria-expanded="false" aria-controls="flush-collapseTwo">
          {{ person.username }} 님이 작성한 리뷰
        </button>
      </h2>
      <div id="flush-collapseTwo" class="accordion-collapse collapse" aria-labelledby="flush-headingTwo">
        <div class="accordion-body">
          {% for review in person.review_set.all %}
            <div class="mb-1">
              <i class="bi bi-chat-dots-fill"></i>
              <a class="profile--a" href="{% url 'posts:detail' review.post.pk %}">{{ review.title }}</a>
            </div>
          {% endfor %}
        </div>
      </div>
    </div>
    <div class="accordion-item">
      <h2 class="accordion-header" id="flush-headingThree">
        <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#flush-collapseThree" aria-expanded="false" aria-controls="flush-collapseThree">
          {{ person.username }}님이 좋아요한 게시글
        </button>
      </h2>
      <div id="flush-collapseThree" class="accordion-collapse collapse" aria-labelledby="flush-headingThree" >
        <div class="accordion-body">
          {% for post in person.like_posts.all %}
            <i class="bi bi-clipboard-heart-fill"></i>
            <a class="profile--a" href="{% url 'posts:detail' post.pk %}">{{ post.title }}</a>
          {% endfor %}
        </div>
      </div>
    </div>
    <div class="accordion-item">
      <h2 class="accordion-header" id="flush-headingfour">
        <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#flush-collapsefour" aria-expanded="false" aria-controls="flush-collapsefour">
          {{ person.username }}님이 좋아요한 댓글
        </button>
      </h2>
      <div id="flush-collapsefour" class="accordion-collapse collapse" aria-labelledby="flush-headingfour" >
        <div class="accordion-body">
          {% for review in person.like_reviews.all %}
            <div >
              <i class="bi bi-chat-heart-fill"></i>
              <a class="profile--a" href="{% url 'posts:detail' review.post.pk %}">{{ review.title }}</a>
            </div>
          {% endfor %}
        </div>
      </div>
    </div>
  </div>
  
  
  {% comment %} <div class="accordion" id="accordionPanelsStayOpenExample">
    <div class="accordion-item">
      <h2 class="accordion-header">
        <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#panelsStayOpen-collapseOne" aria-expanded="true" aria-controls="panelsStayOpen-collapseOne">
          {{ person.username }} 가 작성한 모든 리뷰
        </button>
      </h2>
      <div id="panelsStayOpen-collapseOne" class="accordion-collapse collapse show">
        <div class="accordion-body">
          {% for post in person.post_set.all %}
            <div>{{ post.title }}</div>
          {% endfor %}
        </div>
      </div>
    </div>
    <div class="accordion-item">
      <h2 class="accordion-header" id="panelsStayOpen-headingTwo">
        <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#panelsStayOpen-collapseTwo" aria-expanded="false" aria-controls="panelsStayOpen-collapseTwo">
          {{ person.username }}가 좋아요 한 카페
        </button>
      </h2>
      <div id="panelsStayOpen-collapseTwo" class="accordion-collapse collapse" aria-labelledby="panelsStayOpen-headingTwo">
        <div class="accordion-body">
          {% for post in person.like_posts.all %}
            <div>{{ post.title }}</div>
          {% endfor %}
        </div>
      </div>
    </div>
  </div>   {% endcomment %}

    
    

    
  </div>

{% endblock content %}
{% block script %}
<script src="{% static '/js/profile_modal.js' %}" type="text/javascript"></script>
{% endblock script %}