chat/urls.py
from django.urls import path

from . import views

app_name = 'chat'
urlpatterns = [
    path('', views.index, name='index'),
    path('<str:room_name>/', views.room, name='room'),
]

mango/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from . import views
from django.urls import path
# from accounts.views import LoginTemplateView, MyLoginView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.main, name='main'),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('allauth.urls')),
    path('posts/', include('posts.urls')),
    path('chat/', include('chat.urls')),
    path('my_messages/', include('my_messages.urls')),
    # 구글 정보 받아오기
    # path('login/', LoginTemplateView.as_view(), name='login'),
    # path('accounts/login/', MyLoginView.as_view(), name='account_login'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

my_messages/urls.py
from django.urls import path
from .views import MessageCreateView, MessageListView, SentMessagesView, ReplyMessageView
from . import views

app_name = 'my_messages'
urlpatterns = [
    path('send/', MessageCreateView.as_view(), name='send_message'),
    path('inbox/', MessageListView.as_view(), name='inbox_messages'),
    path('sent/', SentMessagesView.as_view(), name='sent_messages'),
    path('reply/<int:sender_id>/', ReplyMessageView.as_view(), name='reply'),
    path('<int:message_pk>/delete/', views.delete, name='delete'),
]

my_messages/models.py
from django.db import models
from django.conf import settings


class Message(models.Model):
    sender = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='sent_messages')
    receiver = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='received_messages')
    content = models.TextField()
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.sender} -> {self.receiver}: {self.content}"

my_messages/forms.py
from django import forms
from .models import Message
from django.contrib.auth import get_user_model

class MessageForm(forms.ModelForm):
    receiver = forms.ModelChoiceField(queryset=get_user_model().objects.all(), empty_label=None)

    class Meta:
        model = Message
        fields = ['receiver', 'content']
        widgets = {
            'content': forms.Textarea(attrs={'rows': 5}),
        }


class ReplyMessageForm(forms.ModelForm):
    receiver = forms.ModelChoiceField(
        queryset=get_user_model().objects.all(),
        widget=forms.Select(attrs={'readonly': True})
    )
    class Meta:
        model = Message
        fields = ['receiver', 'content']

my_messages/views.py
from django.views.generic.edit import CreateView
from django.views.generic.list import ListView
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import Message
from . forms import ReplyMessageForm
from django.urls import reverse_lazy
from django.shortcuts import get_object_or_404
from django.contrib.auth import get_user_model
from django.shortcuts import redirect


class MessageCreateView(LoginRequiredMixin, CreateView):
    model = Message
    fields = ['receiver', 'content']
    success_url = '/my_messages/sent/'

    def form_valid(self, form):
        form.instance.sender = self.request.user
        return super().form_valid(form)


class MessageListView(LoginRequiredMixin, ListView):
    model = Message
    template_name = 'my_messages/message_list.html'
    context_object_name = 'messages'

    def get_queryset(self):
        return Message.objects.filter(receiver=self.request.user)

class SentMessagesView(LoginRequiredMixin, ListView):
    model = Message
    template_name = 'my_messages/sent_messages.html'
    context_object_name = 'messages'

    def get_queryset(self):
        return Message.objects.filter(sender=self.request.user)


# class ReplyMessageView(LoginRequiredMixin, CreateView):
    # 사용자 선택 가능
    # model = Message
    # fields = ['receiver', 'content']
    # success_url = reverse_lazy('my_messages:sent_messages')
    # def get_initial(self):
    #     initial = super().get_initial()
    #     User = get_user_model()
    #     sender = get_object_or_404(User, id=self.kwargs['sender_id'])
    #     initial['receiver'] = sender.username
    #     return initial

    # def form_valid(self, form):
    #     form.instance.sender = self.request.user
    #     return super().form_valid(form)

    #사용자 선택 불가능
class ReplyMessageView(LoginRequiredMixin, CreateView):
    model = Message
    form_class = ReplyMessageForm
    success_url = reverse_lazy('my_messages:sent_messages')

    def get_initial(self):
        initial = super().get_initial()
        User = get_user_model()
        sender = get_object_or_404(User, id=self.kwargs['sender_id'])
        initial['receiver'] = sender.id
        return initial

    def form_valid(self, form):
        form.instance.sender = self.request.user
        form.instance.receiver = get_object_or_404(get_user_model(), id=self.kwargs['sender_id'])
        return super().form_valid(form)
    
def delete(request, message_pk):
    message = Message.objects.get(pk=message_pk)
    message.delete()
    if message.receiver == request.user:
        return redirect('my_messages:inbox_messages')
    elif message.sender == request.user:
        return redirect ('my_messages:sent_messages')

my_messages/templates/my_messages/message_form.html
{% extends 'base.html' %}
{% load static %}
{% block head %}
  <link rel="stylesheet" type="text/css" href="{% static 'css/message.css' %}">
{% endblock head %}

{% block content %}
<div class="message">
  <h2>쪽지보내기</h2>
  <div class="d-flex flex-column justify-content-center align-items-center">
    <form method="POST">
      {% csrf_token %}
      <div class="message--title" style="text-align:start; margin-left:0;">받는이 : {{ form.receiver }}</div>
      {{ form.content }}
      <button type="submit" class="message--btn--submit">Send</button>
    </form>
  </div>
</div>
{% endblock %}

my_messages/templates/my_messages/message_list.html
{% extends 'base.html' %}
{% load static %}
{% block head %}
  <link rel="stylesheet" type="text/css" href="{% static 'css/message.css' %}">
{% endblock head %}

{% block content %}
  <div class="message">
      <h2>받은 쪽지함<i class="bi bi-envelope-heart ms-2"></i></h2>
    {% if messages %}
      <ul>
        {% for message in messages %}
          <li>
            <div class="message--box">
              <div class="message--sender">보낸이 :<span class="message--sender" style="margin-left:5px;">{{ message.sender }} <a href="{% url 'my_messages:reply' message.sender.id %}">
                <i class="bi bi-envelope-paper-heart chat--btn--txt"></i></a></span>
                <a href="{% url 'my_messages:delete' message.pk %}" onclick="return confirm('삭제하시겠습니까?')">삭제</a>
              </div>
              <div class="message--title">받은시간 :<span class="message--title" style="margin-left:5px; font-family: 'LeeSeoyun';">{{ message.timestamp }}</span></div>
              <div class="message--txt">{{ message.content }}</div>
            </div>
          </li>
        {% endfor %}
      </ul>
    {% else %}
      <p>받은 쪽지가 없습니다.</p>
    {% endif %}
  </div>
{% endblock %}

my_messages/templates/my_messages/sent_messages.html
{% extends 'base.html' %}
{% load static %}
{% block head %}
  <link rel="stylesheet" type="text/css" href="{% static 'css/message.css' %}">
{% endblock head %}

{% block content %}
  <div class="message">
    <h2>보낸 쪽지함 <i class="bi bi-envelope-open-heart  ms-2"></i></h2>
    {% if messages %}
      <ul>
      {% for message in messages %}
        <li>
          <div class="message--box">
            <div class="message--sender">받는이 :<span class="message--sender" style="margin-left:5px;">{{ message.receiver.username }} 
              <a href="{% url 'my_messages:reply' message.receiver.id %}">
              <i class="bi bi-envelope-paper-heart chat--btn--txt"></i></a></span>
              <a href="{% url 'my_messages:delete' message.pk %}" onclick="return confirm('삭제하시겠습니까?')">삭제</a>
            </div>
            <div class="message--title">보낸시간 :<span class="message--title" style="margin-left:5px; font-family: 'LeeSeoyun';">{{ message.timestamp }}</span></div>
            <div class="message--txt">{{ message.content }}</div>
          </div>
        </li>
      {% endfor %}
      </ul>
    {% else %}
      <p>보낸 쪽지가 없습니다.</p>
    {% endif %}
  </div>
{% endblock %}