accounts/urls.py
from django.urls import path
from . import views
# from .views import LoginView


app_name = 'accounts'
urlpatterns = [
    path('login/', views.login, name='login'),
    # path('login-api/', LoginView.as_view(), name='login_api'),
    path('logout/', views.logout, name='logout'),
    path('signup/', views.signup, name='signup'),
    path('delete/', views.delete, name='delete'),
    path('update/', views.update, name='update'),
    path('password/', views.change_password, name='change_password'),
    path('profile/<username>/', views.profile, name='profile'),
    path('<int:user_pk>/follow/', views.follow, name='follow'),
    path('<int:user_pk>/follower/', views.follower, name='follower'),
]

chat/urls.py
from django.urls import path

from . import views

app_name = 'chat'
urlpatterns = [
    path('', views.index, name='index'),
    path('<str:room_name>/', views.room, name='room'),
]

mango/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from . import views
from django.urls import path
# from accounts.views import LoginTemplateView, MyLoginView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.main, name='main'),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('allauth.urls')),
    path('posts/', include('posts.urls')),
    path('chat/', include('chat.urls')),
    path('my_messages/', include('my_messages.urls')),
    # 구글 정보 받아오기
    # path('login/', LoginTemplateView.as_view(), name='login'),
    # path('accounts/login/', MyLoginView.as_view(), name='account_login'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

my_messages/urls.py
from django.urls import path
from .views import MessageCreateView, MessageListView, SentMessagesView, ReplyMessageView
from . import views

app_name = 'my_messages'
urlpatterns = [
    path('send/', MessageCreateView.as_view(), name='send_message'),
    path('inbox/', MessageListView.as_view(), name='inbox_messages'),
    path('sent/', SentMessagesView.as_view(), name='sent_messages'),
    path('reply/<int:sender_id>/', ReplyMessageView.as_view(), name='reply'),
    path('<int:message_pk>/delete/', views.delete, name='delete'),
]

posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'
urlpatterns = [
    path('', views.index, name='index'),
    path('city/', views.city, name='city'),
    path('filtering/<str:sort>/', views.filtering, name='filtering'),
    path('city/filtering/<str:sort>/', views.city_filtering, name='city_filtering'),
    path('create/', views.create, name='create'),
    path('<int:post_pk>/', views.detail, name='detail'),
    path('<int:post_pk>/likes/', views.likes, name='likes'),
    path('<int:post_pk>/delete/', views.delete, name='delete'),
    path('<int:post_pk>/update/', views.update, name='update'),
    path('<int:post_pk>/reviews/', views.review_create, name='review_create'),
    path('<int:post_pk>/reviews/<int:review_pk>', views.review_update, name='review_update'),
    path('<int:post_pk>/reviews/<int:review_pk>/delete/', views.review_delete, name='review_delete'),
    path('<int:post_pk>/reviews/<int:review_pk>/likes/', views.review_likes, name='review_likes'),
    path('search/', views.search, name='search'),
    path('tags/<int:tag_pk>/', views.tagged_posts, name='tagged_posts'),
]

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.4/font/bootstrap-icons.css">
  <title>{% block title %}{% endblock title %}</title>
  {% load static %}
  <link rel="stylesheet" type="text/css" href="{% static 'css/base.css' %}">
  <link rel="icon" href="{% static 'image/bread_favicon.png' %}">
  {% block head %}{% endblock head %}
  {% block style %}{% endblock style %}
</head>
<body>
    <nav>
      <div class="nav--logo">
        <a href="{% url 'main' %}">Mango Cafe</a>
        {% if request.user.is_authenticated %}
          <a href="{% url 'posts:create' %}"><svg width="35px" height="35px" viewBox="0 0 24 24" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" fill="#000000"><g id="SVGRepo_bgCarrier" stroke-width="0"></g><g id="SVGRepo_tracerCarrier" stroke-linecap="round" stroke-linejoin="round"></g><g id="SVGRepo_iconCarrier"> <title>/svg/ic-write</title> <desc>Created with Sketch.</desc> <defs> </defs> <g id="Page-1" stroke="none" stroke-width="1" fill="none" fill-rule="evenodd"> <g id="ic-write" fill="#682C0E"> <path d="M2,21 C2,20.4477153 2.45303631,20 2.99703014,20 L9.00296986,20 C9.5536144,20 10,20.4438648 10,21 C10,21.5522847 9.54696369,22 9.00296986,22 L2.99703014,22 C2.4463856,22 2,21.5561352 2,21 Z M11,21 C11,20.4477153 11.4378814,20 12.0029293,20 L16.9970707,20 C17.5509732,20 18,20.4438648 18,21 C18,21.5522847 17.5621186,22 16.9970707,22 L12.0029293,22 C11.4490268,22 11,21.5561352 11,21 Z M19,21 C19,20.4477153 19.4426603,20 19.9989566,20 L21.0010434,20 C21.5527519,20 22,20.4438648 22,21 C22,21.5522847 21.5573397,22 21.0010434,22 L19.9989566,22 C19.4472481,22 19,21.5561352 19,21 Z" id="Combined-Shape"> </path> <path d="M5.31040616,11.1135896 L8.22224284,13.1135896 L18.8965767,13.1135896 C19.4272224,13.1135896 19.8695896,12.6616798 19.8695896,12.1042207 L19.8695896,10.1229585 C19.8695896,9.55694282 19.4339569,9.11358964 18.8965767,9.11358964 L8.22224284,9.11358964 L5.31040616,11.1135896 Z M1.81081401,11.1135896 L7.63448736,7.11358964 L18.8965767,7.11358964 C20.5093582,7.11358964 21.810814,8.45576807 21.810814,10.1229585 L21.810814,12.1042207 C21.810814,13.7629153 20.5025643,15.1135896 18.8965767,15.1135896 L7.63448736,15.1135896 L1.81081401,11.1135896 Z" id="Rectangle-85" fill-rule="nonzero" transform="translate(11.810814, 11.113590) rotate(-45.000000) translate(-11.810814, -11.113590) "> </path> </g> </g> </g></svg></a>
        {% endif %}
      </div>
      {% block search-bar %}
      <div class="nav--search">
        <form action="{% url 'posts:search' %}" class="search">
          {% csrf_token %}
          <div>
            <input type="search" placeholder='   검색어를 입력하세요!' name='q' style="padding-left:10px;">
            <button class="search-btn" type="submit">
              <svg width="20px" height="20px" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg" fill="none" stroke="#C24914"><g id="SVGRepo_bgCarrier" stroke-width="0"></g><g id="SVGRepo_tracerCarrier" stroke-linecap="round" stroke-linejoin="round"></g><g id="SVGRepo_iconCarrier"> <path fill="#C24914" fill-rule="evenodd" d="M4 9a5 5 0 1110 0A5 5 0 014 9zm5-7a7 7 0 104.2 12.6.999.999 0 00.093.107l3 3a1 1 0 001.414-1.414l-3-3a.999.999 0 00-.107-.093A7 7 0 009 2z"></path> </g></svg>
            </button>
          </div>
        </form>
      </div>
      {% endblock search-bar %}
      <div class="nav--accounts">
        {% if request.user.is_authenticated %}
          {% if user.image %}
          <div class="dropdown">
            <button class="profile--image rounded-circle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
              <img src="{{ user.image.url }}" alt="" class="object-fit-fill profile">
            </button>
            <ul class="dropdown-menu">
              <li><a class="dropdown-item" href="{% url 'accounts:profile' user %}">{{ user }}</a></li>
              <li><a class="dropdown-item" href="{% url 'posts:city' %}"> {{ request.user.region }} 지역 List </a></li>
              <li><a class="dropdown-item" href="{% url 'my_messages:inbox_messages' %}"> 받은 쪽지함<i class="bi bi-envelope-heart  ms-2"></i> </a></li>
              <li><a class="dropdown-item" href="{% url 'my_messages:sent_messages' %}"> 보낸 쪽지함<i class="bi bi-envelope-open-heart  ms-2"></i> </a></li>
              <li><a class="dropdown-item" href="{% url 'accounts:logout' %}">Logout</a></li>
            </ul>
          </div>
          {% else %}
          <div class="dropdown">
            <button class="profile--image rounded-circle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
              <img src="{% static 'image/profile-none.png' %}" alt="" class="object-fit-fill profile">
            </button>
            <ul class="dropdown-menu">
              <li><a class="dropdown-item" href="{% url 'accounts:profile' user %}">{{ user }}</a></li>
              <li><a class="dropdown-item" href="{% url 'posts:city' %}"> {{ request.user.region }} 지역 List </a></li>
              <li><a class="dropdown-item" href="{% url 'my_messages:inbox_messages' %}"> 받은 쪽지함<i class="bi bi-envelope-heart ms-2"></i> </a></li>
              <li><a class="dropdown-item" href="{% url 'my_messages:sent_messages' %}"> 보낸 쪽지함<i class="bi bi-envelope-open-heart  ms-2"></i> </a></li>
              <li><a class="dropdown-item" href="{% url 'accounts:logout' %}">Logout</a></li>
            </ul>
          </div>
          {% endif %}
        {% else %}
        <div class="dropdown">
          <button class="profile--image rounded-circle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
            <img src="{% static 'image/profile-none.png' %}" alt="" class="object-fit-fill profile">
          </button>
          <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="{% url 'accounts:login' %}">Login</a></li>
            <li><a class="dropdown-item" href="{% url 'accounts:signup' %}">Join</a></li>
          </ul>
        </div>
        {% endif %}
      </div>
    </nav>
    <section>
      {% block content %}
      {% endblock content %}
    </section>
    <footer>
      <div class="footer--txt">
        <a href="https://github.com/haelim12">고해림</a>
        <a href="https://github.com/JiSuMun">문지수</a>
        <a href="https://github.com/mungjimangji">장민지</a>
        <a href="https://github.com/sodamjeong">정소담</a>
        <p>KDT 풀스택 2기 맛집2조 Copyright 2023. All Rights Reserved.</p>
      </div>
    </footer>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>
  {% block script %}
  {% endblock script %}
</body>
</html>

templates/main.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Main{% endblock title %}
{% block head %}
  <link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
{% endblock head %}

{% block content %}
<div class="main--content">
  <div class="content--box">
    <div class="top--box"> Cafe TOP5</div>
    <button id="prevbtn" class="main--btn--left"></button>
      <div class="main--carousel--box">
        <div class="main--category">
          <div class="main--carousel" id="cafe-carousel">
            {% for post,image in post_images %}
              <a href="{% url 'posts:detail' post.pk %}" class="main--card">
                <div class="card--item">
                    {% if image %}
                      <img src="{{ image.image.url }}" alt="" class="main--img">
                    {% else %}
                      <img src="{% static 'image/none_img.png' %}" alt=""  class="main--img">
                    {% endif %}
                  <div class="main--info--box">
                    <div class="main--title">
                      {{ forloop.counter }}위 
                      {{ post.title }}
                    </div>
                    <p> {{ post.address }}</p>
                    <div class="heart--box">
                      {% if request.user.is_authenticated %}
                        <form id="likes-form-{{ post.pk }}" data-post-id="{{ post.pk }}" class="main--heart">
                          {% csrf_token %}
                          {% if request.user in post.like_users.all %}
                              <button class="btn btn-link text-danger p-0" type="submit">
                                <i class="bi bi-suit-heart-fill main--heart"></i>
                              </button>
                          {% else %}
                              <button class="btn btn-link text-danger p-0" type="submit">
                                <i class="bi bi-suit-heart main--heart"></i>
                              </button>
                          {% endif %}
                        </form>
                      {% else %}
                        <button class="btn btn-link text-secondary p-0" disabled>
                          <i class="bi bi-suit-heart main--heart"></i>
                        </button>
                      {% endif %}
                    </div>
                  </div>
                </div>
              </a>
            {% endfor %}
          </div>
        </div>
      </div>
    <button id="nextbtn" class="main--btn--right "></button>
  </div>
  <div class="content--box">
    <div class="top--box"> Bakery TOP5</div>
    <button id="prevbtnb" class="main--btn--left"></button>
      <div class="main--carousel--box">
        <div class="main--category">
          <div class="main--carousel" id="bakery-carousel">
            {% for post,image in bakery_post_images %}
              <a href="{% url 'posts:detail' post.pk %}" class="main--card">
                <div class="card--item">
                    {% if image %}
                      <img src="{{ image.image.url }}" alt="" class="main--img">
                    {% else %}
                      <img src="{% static 'image/none_img.png' %}" alt=""  class="main--img">
                    {% endif %}
                  <div class="main--info--box">
                    <div class="main--title">
                      {{ forloop.counter }}위 
                      {{ post.title }}
                    </div>
                    <p> {{ post.address }}</p>
                    <div class="heart--box">
                      {% if request.user.is_authenticated %}
                        <form id="likes-form-{{ post.pk }}" data-post-id="{{ post.pk }}" class="main--heart">
                          {% csrf_token %}
                          {% if request.user in post.like_users.all %}
                              <button class="btn btn-link text-danger p-0" type="submit">
                                <i class="bi bi-suit-heart-fill main--heart"></i>
                              </button>
                          {% else %}
                              <button class="btn btn-link text-danger p-0" type="submit">
                                <i class="bi bi-suit-heart main--heart"></i>
                              </button>
                          {% endif %}
                        </form>
                      {% else %}
                        <button class="btn btn-link text-secondary p-0" disabled>
                          <i class="bi bi-suit-heart main--heart"></i>
                        </button>
                      {% endif %}
                    </div>
                  </div>
                </div>
              </a>
            {% endfor %}
          </div>
        </div>
      </div>
    <button id="nextbtnb" class="main--btn--right "></button>
  </div>
</div>

{% endblock content %}

{% block script %}

<script>

  class cafeCarousel {
    constructor() {
      this.index = 0;
      this.$cafecarousel = document.querySelector("#cafe-carousel");
      this.$prevButton = document.querySelector("#prevbtn");
      this.$nextButton = document.querySelector("#nextbtn");
  
      this.$prevButton.addEventListener("click", () => {
        this.prev();
      });
  
      this.$nextButton.addEventListener("click", () => {
        this.next();
      });
  
    
      if (this.index === 0) {
        this.$prevButton.hidden = true;
      }
      
      if (this.$cafecarousel.childElementCount <= 1) {
        this.$nextButton.hidden = true;
      }
  
      if (this.index === 0 && this.$cafecarousel.childElementCount > 1) {
        this.$nextButton.hidden = false;
      }
    }
  
    prev() {
      if (this.index <= 0) return;
      this.index -= 1;
  
      this.$cafecarousel.style.transform = `translate3d(-${
        600 * this.index
      }px, 0, 0)`;
  
      if (this.index <= 0) {
        this.$prevButton.hidden = true;
      } else {
        this.$prevButton.hidden = false;
      }
      if (this.index >= this.$cafecarousel.childElementCount) {
        this.$nextButton.hidden = true;
      } else {
        this.$nextButton.hidden = false;
      }
    }
  
    next() {
      if (this.index >= this.$cafecarousel.childElementCount) return;
      this.index += 1;
  
      this.$cafecarousel.style.transform = `translate3d(-${
        600 * this.index
      }px, 0, 0)`;
      if (this.index <= 0) {
        this.$prevButton.hidden = true;
      } else {
        this.$prevButton.hidden = false;
      }
      if (this.index >= this.$cafecarousel.childElementCount-1) {
        this.$nextButton.hidden = true;
      } else {
        this.$nextButton.hidden = false;
      }
    }
  }
  const cafecarousel = new cafeCarousel();

</script>
<script src="{% static '/js/main_bakerycarousel.js' %}" type="text/javascript"></script>
<script src="{% static '/js/main_likes.js' %}" type="text/javascript"></script>



{% endblock script %}