accounts/urls.py
from django.urls import path
from . import views
# from .views import LoginView


app_name = 'accounts'
urlpatterns = [
    path('login/', views.login, name='login'),
    # path('login-api/', LoginView.as_view(), name='login_api'),
    path('logout/', views.logout, name='logout'),
    path('signup/', views.signup, name='signup'),
    path('delete/', views.delete, name='delete'),
    path('update/', views.update, name='update'),
    path('password/', views.change_password, name='change_password'),
    path('profile/<username>/', views.profile, name='profile'),
    path('<int:user_pk>/follow/', views.follow, name='follow'),
    path('<int:user_pk>/follower/', views.follower, name='follower'),
]

chat/urls.py
from django.urls import path

from . import views

app_name = 'chat'
urlpatterns = [
    path('', views.index, name='index'),
    path('<str:room_name>/', views.room, name='room'),
]

mango/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from . import views
from django.urls import path
# from accounts.views import LoginTemplateView, MyLoginView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.main, name='main'),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('allauth.urls')),
    path('posts/', include('posts.urls')),
    path('chat/', include('chat.urls')),
    path('my_messages/', include('my_messages.urls')),
    # 구글 정보 받아오기
    # path('login/', LoginTemplateView.as_view(), name='login'),
    # path('accounts/login/', MyLoginView.as_view(), name='account_login'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

my_messages/urls.py
from django.urls import path
from .views import MessageCreateView, MessageListView, SentMessagesView, ReplyMessageView
from . import views

app_name = 'my_messages'
urlpatterns = [
    path('send/', MessageCreateView.as_view(), name='send_message'),
    path('inbox/', MessageListView.as_view(), name='inbox_messages'),
    path('sent/', SentMessagesView.as_view(), name='sent_messages'),
    path('reply/<int:sender_id>/', ReplyMessageView.as_view(), name='reply'),
    path('<int:message_pk>/delete/', views.delete, name='delete'),
]

posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'
urlpatterns = [
    path('', views.index, name='index'),
    path('city/', views.city, name='city'),
    path('filtering/<str:sort>/', views.filtering, name='filtering'),
    path('city/filtering/<str:sort>/', views.city_filtering, name='city_filtering'),
    path('create/', views.create, name='create'),
    path('<int:post_pk>/', views.detail, name='detail'),
    path('<int:post_pk>/likes/', views.likes, name='likes'),
    path('<int:post_pk>/delete/', views.delete, name='delete'),
    path('<int:post_pk>/update/', views.update, name='update'),
    path('<int:post_pk>/reviews/', views.review_create, name='review_create'),
    path('<int:post_pk>/reviews/<int:review_pk>', views.review_update, name='review_update'),
    path('<int:post_pk>/reviews/<int:review_pk>/delete/', views.review_delete, name='review_delete'),
    path('<int:post_pk>/reviews/<int:review_pk>/likes/', views.review_likes, name='review_likes'),
    path('search/', views.search, name='search'),
    path('tags/<int:tag_pk>/', views.tagged_posts, name='tagged_posts'),
]

posts/models.py
from django.db import models
from django.conf import settings
from imagekit.models import ProcessedImageField
from imagekit.processors import ResizeToFill
from django.core.validators import RegexValidator
from django.core.validators import MinValueValidator, MaxValueValidator
from django.utils import timezone
from datetime import timedelta,datetime
from django.conf import settings
import os
from taggit.managers import TaggableManager
from django.urls import reverse
from django.utils.text import slugify


class Post(models.Model):
    CAFE = 'cafe'
    BAKERY = 'bakery'
    CATEGORY_CHOICES = [
        (CAFE, 'Cafe'),
        (BAKERY, 'Bakery'),
    ]
    SEOUL = '서울'
    INCHEON = '인천'
    BUSAN = '부산'
    ULSAN = '울산'
    DAEGU = '대구'
    GWANGJU = '광주'
    DAEJEON = '대전'
    JEJU = '제주도'
    GYEONGGI = '경기도'
    GANGWON = '강원도'
    CHUNGBUK = '충청북도'
    CHUNGNAM = '충청남도'
    JEONBUK = '전라북도'
    JEONNAM = '전라남도'
    GYEONGBUK = '경상북도'
    GYEONGNAM = '경상남도'    
    CITY_CHOICES = [
        (SEOUL, '서울'), (INCHEON, '인천'), (BUSAN, '부산'), (ULSAN, '울산'), (DAEGU, '대구'), (GWANGJU, '광주'), (DAEJEON, '대전'), (JEJU, '제주도'), (GYEONGGI, '경기도'), (GANGWON, '강원도'), (CHUNGBUK, '충청북도'), (CHUNGNAM, '충청남도'), (JEONBUK, '전라북도'), (JEONNAM, '전라남도'), (GYEONGBUK, '경상북도'),(GYEONGNAM, '경상남도'),
    ]

    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    like_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='like_posts')
    title = models.CharField(max_length=50)
    category = models.CharField(max_length=10, choices=CATEGORY_CHOICES)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    address = models.CharField(max_length=200)
    phoneNumberRegex = RegexValidator(regex=r'^0[1-9]\d{0,2}-\d{3,4}-\d{4}$')
    phone = models.CharField(validators=[phoneNumberRegex], max_length=14)
    parking = models.CharField(max_length=50, default='가게 문의')
    business_time = models.CharField(max_length=50, default='가게 문의')
    menu = models.TextField()
    insta = models.URLField(blank=True, null=True)
    home = models.URLField(blank=True, null=True)
    city = models.CharField(max_length=10, choices=CITY_CHOICES)
    tags = TaggableManager()
    rating = models.DecimalField(default=0, max_digits=5, decimal_places=1)

    # slug = models.SlugField(allow_unicode=True)

    # def save(self, *args, **kwargs):
    #     if not self.slug:
    #         self.slug = slugify(self.title, allow_unicode=True)
    #     super(Post, self).save(*args, **kwargs)


    def __str__(self):
        return self.title

    @property
    def created_string(self):
        time = datetime.now(tz=timezone.utc) - self.created_at

        if time < timedelta(minutes=1):
            return '방금 전'
        elif time < timedelta(hours=1):
            return str(int(time.seconds / 60)) + '분 전'
        elif time < timedelta(days=1):
            return str(int(time.seconds / 3600)) + '시간 전'
        elif time < timedelta(days=7):
            time = datetime.now(tz=timezone.utc).date() - self.created_at.date()
            return str(time.days) + '일 전'
        else:
            return self.strftime('%Y-%m-%d')
    
    def delete(self, *args, **kargs):
        images = self.postimage_set.all()
        for image in images:
            image.delete()
        super(Post, self).delete(*args, **kargs)

class PostImage(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)

    def post_image_path(instance, filename):
        return f'post/{instance.post.pk}/{filename}'
    image = ProcessedImageField(
        upload_to=post_image_path,
        blank=True, 
        null=True,
        options={'quality':90})
    
    def delete(self, *args, **kargs):
        if self.image:
            os.remove(os.path.join(settings.MEDIA_ROOT, self.image.name))
            dir_path = os.path.dirname(os.path.join(settings.MEDIA_ROOT, self.image.name))
            if not os.listdir(dir_path):
                os.rmdir(dir_path)
        super(PostImage, self).delete(*args, **kargs)


    # def delete(self, *args, **kargs):
    #     if self.image:
    #         image_path = os.path.join(settings.MEDIA_ROOT, self.image.name)
    #         if os.path.exists(image_path):
    #             os.remove(image_path)
    #             dir_path = os.path.dirname(image_path)
    #             if not os.listdir(dir_path):
    #                 os.rmdir(dir_path)
    #     super(PostImage, self).delete(*args, **kargs)


class Review(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='reviews')
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    EMOTIONS = (
        (1, '별로에요'),
        (2, '괜찮아요'),
        (3, '맛있어요'),
    )
    emotion = models.IntegerField(choices=EMOTIONS, default=3)
    title = models.CharField(max_length=50)
    content = models.TextField()
    rating = models.IntegerField(default=5, validators=[MinValueValidator(1), MaxValueValidator(5)])
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    like_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='like_reviews')

    @property
    def created_string(self):
        time = datetime.now(tz=timezone.utc) - self.created_at

        if time < timedelta(minutes=1):
            return '방금 전'
        elif time < timedelta(hours=1):
            return str(int(time.seconds / 60)) + '분 전'
        elif time < timedelta(days=1):
            return str(int(time.seconds / 3600)) + '시간 전'
        elif time < timedelta(days=7):
            time = datetime.now(tz=timezone.utc).date() - self.created_at.date()
            return str(time.days) + '일 전'
        else:
            return self.strftime('%Y-%m-%d')
    
    def save(self, *args, **kwargs):
        self.post.rating = (self.post.rating*self.post.reviews.count() + self.rating) / (self.post.reviews.count() + 1)
        self.post.save()
        super(Review, self).save(*args, **kwargs)

# from django.core.exceptions import ValidationError  

# def validate_image_count(value):
#     if ReviewImage.objects.filter(review=value.review).count() > 3:
#         raise ValidationError('이미지는 최대 3개까지만 업로드 가능합니다.')


class ReviewImage(models.Model):
    review = models.ForeignKey(Review, on_delete=models.CASCADE)

    def review_image_path(instance, filename):
        return f'review/{instance.review.pk}/{filename}'
    image = ProcessedImageField(
        upload_to=review_image_path,
        blank=True, 
        null=True, 
        processors=[ResizeToFill(100, 100)], 
        options={'quality':100},)
    
    def delete(self, *args, **kargs):
        if self.image:
            os.remove(os.path.join(settings.MEDIA_ROOT, self.image.name))
        super(ReviewImage, self).delete(*args, **kargs)

    def save(self, *args, **kwargs):
        if self.id:
            old_post = ReviewImage.objects.get(id=self.id)
            if self.image != old_post.image:
                if old_post.image:
                    os.remove(os.path.join(settings.MEDIA_ROOT, old_post.image.name))
        super(ReviewImage, self).save(*args, **kwargs)
    

posts/forms.py
from django import forms
from django.forms.widgets import ClearableFileInput
from .models import Post, Review, PostImage, ReviewImage
from taggit.forms import TagField, TagWidget
from taggit.managers import TaggableManager
from django.conf import settings
import os


class PostForm(forms.ModelForm):
    title = forms.CharField(
        max_length=50, 
        label='가게명(필수)', 
        widget=forms.TextInput(
            attrs={
                'required': True,
                'placeholder': '제목을 입력해주세요.',
                'class': 'form-control',
                'style' : 'width: 600px;'
            }
        )
        
    )
    address = forms.CharField(
        max_length=200, 
        label='주소(필수)', 
        widget=forms.TextInput(
            attrs={
                'required': True, 
                'placeholder': '정확한 주소를 입력해주세요.', 
                'class': 'form-control',
                'style' : 'width: 600px;'
            }
        )
    )
    category = forms.ChoiceField(
        choices=Post.CATEGORY_CHOICES, 
        label='카테고리(필수)', 
        widget=forms.Select(
            attrs={
                'required': True,
                'class': 'form-select',
                'style' : 'width: 600px;'
            }
        )
    )
    menu = forms.CharField(
        max_length=200, 
        label='메뉴(필수)', 
        widget=forms.Textarea(
            attrs={
                'required': True,
                'placeholder': '메뉴를 입력해주세요.', 
                'class': 'form-control',
                'style' : 'width: 600px;'
            }
        )
    )
    city = forms.ChoiceField(
        choices=Post.CITY_CHOICES, 
        label='지역(필수)', 
        widget=forms.Select(
            attrs={
                'required': True,
                'class': 'form-select',
                'style' : 'width: 600px;'
            }
        )
    )

    phone = forms.CharField(
        max_length=14, 
        required = False,
        label='전화번호(필수)', 
        widget=forms.TextInput(
            attrs={
                'placeholder': '-을 포함해주세요.',
                'class': 'form-control',
                'style' : 'width: 600px;'
                
            }
        )
    )             
    parking = forms.CharField(
        label='주차', 
        widget=forms.TextInput(
            attrs={
                'value': '가게문의',
                'class': 'form-control',
                'style' : 'width: 600px;',
            }
        )
    )
    business_time = forms.CharField(
        label='영업시간',
        widget=forms.TextInput(
            attrs={  
                'value': '가게문의',
                'class': 'form-control',
                'style' : 'width: 600px;'
            }
        )
    )
    insta = forms.CharField(
        label='인스타그램', 
        required = False,
        widget=forms.TextInput(
            attrs={
                'placeholder': '인스타그램 주소를 입력해주세요.', 
                'class': 'form-control',
                'style' : 'width: 600px;'
            }
        )
    )
    home = forms.CharField(
        label='홈페이지', 
        required = False,
        widget=forms.TextInput(
            attrs={
                'placeholder': '홈페이지 주소를 입력해주세요.',
                'class': 'form-control',
                'style' : 'width: 600px;'
            }
        )
    )
    class Meta:
        model = Post
        fields = ('title', 'category', 'city', 'address', 'phone', 'parking', 'business_time', 'menu', 'insta', 'home', 'tags')
        widgets = {
            'tags': TagWidget(attrs={
                'class': 'form-control', 
                'style' : 'width: 600px;',
                'placeholder': "태그는 콤마(,)로 구분해주세요.",
                }),
        }
        labels = {
        'tags': '#해시태그(필수):',
        }
        help_texts = {
            'tags': '',
        }

class CustomClearableFileInput(ClearableFileInput):
    template_name = 'posts/custom_clearable_file_input.html'

class PostImageForm(forms.ModelForm):
    image = forms.ImageField(
        label='관련 이미지(필수)',
        widget=CustomClearableFileInput(
            attrs={
                'multiple': True, 
                'class': 'form-control', 
                'style': 'width: 600px;',
            }
        ),
    )

    class Meta:
        model = PostImage
        fields = ('image',)

class DeleteImageForm(forms.Form):
    delete_images = forms.MultipleChoiceField(
        label='삭제할 이미지 선택',
        required = False,
        widget=forms.CheckboxSelectMultiple,
        choices=[]
    )

    def __init__(self, post, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['delete_images'].choices = [
            (image.pk, image.image.name) for image in PostImage.objects.filter(post=post)
        ]

    def clean(self):
        cleaned_data = super().clean()
        delete_ids = cleaned_data.get('delete_images')
        if delete_ids:
            images = PostImage.objects.filter(pk__in=delete_ids)
            for image in images:
                os.remove(os.path.join(settings.MEDIA_ROOT, image.image.path))
            images.delete()

class ReviewForm(forms.ModelForm):
    title = forms.CharField(
        max_length=50, 
        label='리뷰 제목', 
        widget=forms.TextInput(
            attrs={
                'required': True,
                'placeholder': '제목을 입력해주세요.',
                'class': 'form-control',
                'style' : 'width: 400px;'
            }
        )
    )
    content = forms.CharField(
        max_length=200, 
        label='리뷰 내용', 
        widget=forms.Textarea(
            attrs={
                'class': 'form-control',
                'placeholder': '내용을 입력해주세요.',
                'style' : 'width: 400px;'
            }
        )
    )
    class Meta:
        model = Review
        fields = ('title', 'content',)
        

class ReviewImageForm(forms.ModelForm):
    image = forms.ImageField(
        label='이미지(최대 3장)',
        required=False,
        widget=CustomClearableFileInput(
            attrs={
                'multiple': True, 
                'class': 'form-control', 
                'style' : 'width: 400px;'
            }
        ),
    )

    class Meta:
        model = ReviewImage
        fields = ('image',)

    def clean(self):
        cleaned_data = super().clean()
        images = self.files.getlist('image')

        if images:
            if len(images) > 3:
                raise forms.ValidationError("이미지는 최대 3개까지만 선택 가능합니다.")


class DeleteReviewImageForm(forms.Form):
    delete_images = forms.MultipleChoiceField(
        label='삭제할 이미지 선택',
        required = False,
        widget=forms.CheckboxSelectMultiple,
        choices=[]
    )

    def __init__(self, review, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['delete_images'].choices = [
            (image.pk, image.image.name) for image in ReviewImage.objects.filter(review=review)
        ]

    def clean(self):
        cleaned_data = super().clean()
        delete_ids = cleaned_data.get('delete_images')
        if delete_ids:
            images = ReviewImage.objects.filter(pk__in=delete_ids)
            for image in images:
                os.remove(os.path.join(settings.MEDIA_ROOT, image.image.path))
            images.delete()

posts/templates/posts/create.html
{% extends 'base.html' %}
{% block title %}
Write
{% endblock title %}
{% block content %}

  <div class="posts--box">
    <div class="posts--create">
      <h1>게시글을 작성해주세요!</h1>
      <form action="{% url 'posts:create' %}" method='POST' enctype='multipart/form-data'>
        {% csrf_token %}
        {{ post_form.as_p }}
        {{ image_form.as_p }}
        <input class="posts--btn" type="submit" value="등록">
        <input type="submit" value="뒤로가기" class="posts--btn" onclick=window.history.back()>
      </form>
    </div>
  </div>
{% endblock content %}

posts/templates/posts/index.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
List
{% endblock title %}
{% block style %}
<style>
  section {
    position: relative;
  }
</style>
{% endblock style %}
{% block content %}
  <div class="index--page">
    <div class="sidebar">
      <h2>전체 List</h2>
      <ul>
        <li><a href="{% url 'posts:index' %}"><i class="bi bi-list"></i> 최신순</a></li>
        <li><a href="{% url 'posts:filtering' '별점순' %}"><i class="bi bi-star"></i> 별점순</a></li>
        <li><a href="{% url 'posts:filtering' '리뷰순' %}"><i class="bi bi-chat-dots"></i> 리뷰순</a></li>
        <li><a href="{% url 'posts:filtering' '좋아요순' %}"><i class="bi bi-chat-heart"></i> 좋아요순</a></li>
        <li><a href="{% url 'posts:city' %}"><i class="bi bi-geo-alt"></i> 선호지역만 보기</a></li>
      </ul>
    </div>

    <div class="posts">
      <h2>Cafe</h2>
      <div class="posts--carousel--box">
        <button id="prevbtn" class="carousel--btn--left"></button>
        <div class="posts--category">
          <div class="carousel" id="cafe-carousel">
            {% for post,image in post_images %}
              {% if post.category == 'cafe' %}
              <a href="{% url 'posts:detail' post.pk %}" class="index--card">
                <div class="index--card--box">
                  <div class="index--image--box">
                    {% if image %}
                      <img src="{{ image.image.url }}" alt="" class="index--img object-fit-fill">
                    {% else %}
                      <img src="{% static 'image/none_img.png' %}" alt=""  class="index--img object-fit-fill">
                    {% endif %}
                    <div class="index--rating"><img src="{% static 'image/allstar.png' %}" class="index--star" alt="">{{ post.rating }}</div>
                  </div>
                  <div class="index--info--box ">
                    <div class="index--title">
                      {{ post.title }}
                    </div>
                    <div class="index--txt p-1">
                      <p class="index--txt"> {{ post.address }}</p>
                    </div>
                    <div class="d-flex justify-content-between index--txt p-1">
                      <p class="index--txt">{{ post.menu }}</p>
                      <div class='d-flex gap-1'>
                        {% if request.user.is_authenticated %}
                          <form id="likes-form-{{ post.pk }}" data-post-id="{{ post.pk }}" class="index--heart">
                            {% csrf_token %}
                            {% if request.user in post.like_users.all %}
                                <button class="btn btn-link text-danger p-0" type="submit">
                                  <i class="bi bi-suit-heart-fill"></i>
                                </button>
                            {% else %}
                                <button class="btn btn-link text-danger p-0" type="submit">
                                  <i class="bi bi-suit-heart"></i>
                                </button>
                            {% endif %}
                          </form>
                        {% else %}
                          <button class="btn btn-link text-secondary p-0" disabled>
                            <i class="bi bi-suit-heart"></i>
                          </button>
                        {% endif %}
                        <span id="likes-count">{{ post.like_users.all|length }}</span>
                      </div>
                    </div>
                  </div>
                </div>
              </a>
              {% endif %}
            {% endfor %}
          </div>
        </div>
        <button id="nextbtn" class="carousel--btn--right"></button>
      </div>
      <h2>Bakery</h2>
      <div class="posts--carousel--box">
        <button id="prevbtnb" class="carousel--btn--left"></button>
        <div class="posts--category">
          <div class="carousel" id="bakery-carousel">
            {% for post,image in post_images %}
              {% if post.category == 'bakery' %}
              <a href="{% url 'posts:detail' post.pk %}" class="index--card">
                <div class="index--card--box">
                  <div class="index--image--box">
                    {% if image %}
                      <img src="{{ image.image.url }}" alt="" class="index--img object-fit-fill">
                    {% else %}
                      <img src="{% static 'image/none_img.png' %}" alt=""  class="index--img object-fit-fill">
                    {% endif %}
                    <div class="index--rating"><img src="{% static 'image/allstar.png' %}" class="index--star" alt="">{{ post.rating }}</div>
                  </div>
                  <div class="index--info--box ">
                    <div class="index--title">
                      {{ post.title }}
                    </div>
                    <div class="index--txt p-1">
                      <p class="index--txt"> {{ post.address }} </p>
                    </div>
                    <div class="d-flex justify-content-between index--txt p-1">
                      <p class="index--txt">{{ post.menu }}</p>
                      <div class='d-flex gap-1'>
                        {% if request.user.is_authenticated %}
                          <form id="likes-form-{{ post.pk }}" data-post-id="{{ post.pk }}" class="index--heart">
                            {% csrf_token %}
                            {% if request.user in post.like_users.all %}
                                <button class="btn btn-link text-danger p-0" type="submit">
                                  <i class="bi bi-suit-heart-fill"></i>
                                </button>
                            {% else %}
                                <button class="btn btn-link text-danger p-0" type="submit">
                                  <i class="bi bi-suit-heart"></i>
                                </button>
                            {% endif %}
                          </form>
                        {% else %}
                          <button class="btn btn-link text-secondary p-0" disabled>
                            <i class="bi bi-suit-heart"></i>
                          </button>
                        {% endif %}
                        <span id="likes-count">{{ post.like_users.all|length }}</span>
                      </div>
                    </div>
                  </div>
                </div>
              </a>
              {% endif %}
            {% endfor %}
          </div>
        </div>
        <button id="nextbtnb" class="carousel--btn--right"></button>
      </div>
    </div>
  </div>
  <div class="message--btn"><a href="{% url 'my_messages:send_message' %}" class="chat--btn--txt"><i class="bi bi-envelope-heart"></i></a></div>
  <div class="chat--btn"><a href="{% url 'chat:index' %}" class="chat--btn--txt"><i class="bi bi-chat-square-heart"></i></a></div>
{% endblock content %}

{% block script %}
<script src="{% static '/js/index_likes.js' %}" type="text/javascript"></script>
<script src="{% static '/js/index_cafecarousel.js' %}" type="text/javascript"></script>
<script src="{% static '/js/index_bakerycarousel.js' %}" type="text/javascript"></script>
{% endblock script %}

posts/templates/posts/review_update.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
Review 수정
{% endblock title %}
{% block head %}
  <link rel="stylesheet" type="text/css" href="{% static 'css/detail.css' %}">
{% endblock head %}
{% block style %}
<style>
  .star-rating input[name="rating"] {
    display: none;
  }

  .emoji-rating label.selected {
    transform: scale(1.1);
    box-shadow: 0 0 5px rgba(0, 0, 0, 0.3);
    border-radius: 50px;
  }
  
  .emoji-rating input[name="emotion"] {
    display: none;
  }

  #id_delete_images {
    list-style: none;
    width: 400px;
  }
</style>
{% endblock style %}
{% block content %}
<div class="posts--box">
  <div class="posts--create">
      <h1>리뷰를 수정해주세요.</h1>
        <form action="{% url 'posts:review_update' post.pk review.pk %}" method='POST' enctype='multipart/form-data'>
          {% csrf_token %}
          <label for="rating">별점:</label>
          <div class="star-rating">
            <input id="star-1" name="rating" type="radio" value="1" />
            <label class="star-label rating--orange" for="star-1" title="1 star"></label>
            <input id="star-2" name="rating" type="radio" value="2" />
            <label class="star-label rating--orange" for="star-2" title="2 stars"></label>
            <input id="star-3" name="rating" type="radio" value="3" />
            <label class="star-label rating--orange" for="star-3" title="3 stars"></label>
            <input id="star-4" name="rating" type="radio" value="4" />
            <label class="star-label rating--orange" for="star-4" title="4 stars"></label>
            <input id="star-5" name="rating" type="radio" value="5" />
            <label class="star-label rating--orange" for="star-5" title="5 stars"></label>
          </div>
          {{ review_form.as_p}}
          <label for="emotion">만족도:</label>
          <div class="emoji-rating">
            <input id="emoji-3" name="emotion" type="radio" value="3" />
            <label class="emoji-label review--imoge1" for="emoji-3" title="맛있어요"></label>
            <input id="emoji-2" name="emotion" type="radio" value="2" />
            <label class="emoji-label review--imoge2" for="emoji-2" title="괜찮아요"></label>
            <input id="emoji-1" name="emotion" type="radio" value="1" />
            <label class="emoji-label review--imoge3" for="emoji-1" title="별로예요"></label>
          </div>
          {{ image_form.as_p}}
          {{ delete_form.as_p }}
          <input class="posts--reviewBtn" type="submit" value="리뷰등록">
          <input type="submit" value="뒤로가기" class="posts--reviewBtn" onclick=window.history.back()>
        </form>
    </div>
  </div>
{% endblock content %}

{% block script %}
<script src="{% static '/js/review.js' %}" type="text/javascript"></script>
{% endblock script %}

posts/templates/posts/update.html
{% extends 'base.html' %}

{% block title %}
  Update
{% endblock title %}


{% block content %}
  <div class="posts--box">
    <div class="posts--create">
      <h1>게시글을 수정해주세요.</h1>
        <form action="{% url 'posts:update' post.pk %}" method='POST' enctype='multipart/form-data'>
          {% csrf_token %}
          {{ post_form.as_p}}
          {{ image_form.as_p }}
          {{ delete_form.as_p }}
          <input class="posts--btn" type="submit">
        </form>
    </div>
  </div>
{% endblock content %}

{% block script %}
<script>



</script>
{% endblock script %}